# Generated by Django 2.2 on 2021-04-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_todo_assigned_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user_assigned',
        ),
    ]
